# Variable for setting up the AWS env
key_name: stock # name of the key, which is used for connection
region: eu-north-1
image: ami-01996625fff6b8fcc # ubuntu 18.04
name: wordpress # name for the EC2 which is visible in the web console
vpc_name: VPC for Wordpress #name for the new vpc
sg_name: SG for Wordpress # Name for the Security Group to be used
size: t3.small # ec2 size
wordpress_subnet: 10.10.1.0/24 # wordpress subnet
ansible_ssh_private_key_file: /home/kasutja/.ssh/stock.pem  # key file, which ansible will use when loggin into the ec2
ansible_user: ubuntu  # user, which ansible will use when logging into the ec2

#HTTP Settings
http_host: "your_domain" # for example www.kullakamakas.com
http_conf: "your_domain.conf"
http_port: "80"

# Indreku public key file
pub_file: /home/ubuntu/indrek.pub # Public key which You want to upload to the newly created ec2 so that the users could connect