---
- name: Install the WP CLI, create a user to run it and activate plugins
  hosts: wordpress  # defined in the hosts file
  gather_facts: true  
  become: true  # we configure things as root
  vars_files:
    - "./group_vars/vars.yml" # variables for the ec2 name, region, ami, web site, etc

  tasks:

    - name: Install WP CLI, create WP user and activate all plugins
      shell: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
        useradd -g www-data {{ wp_user }}
        mkdir /home/{{ wp_user }}
        chown -R {{ wp_user }}:www-data /home/{{ wp_user }}
        sudo -u {{ wp_user }} -i -- wp plugin activate --path='/var/www/{{ http_host }}/' --all
        
 
