- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "./group_vars/vars.yml" # variables for the ec2 name, region, ami,etc
 
  roles:
    - vpc
    - ec2

- hosts: wordpress
  gather_facts: true
  become: true  # we configure things as root
  vars_files:
    - "./group_vars/vault"   # this includes credentials for MySQL
    - "./group_vars/vars.yml" # variables for the ec2 name, region, ami, web site, etc

  roles:
    - updates
    - apache
    - mysql
    - wordpress
    - key
    
